language: node_js
node_js:
- '6'
env:
- NODE_ENV=ci
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn run build
- npm run test

notifications:
  slack:
    secure: JAA87Ovg97Xc3dUerapIHbpTYD1pZ5s6mekuycwW8QVmyrCst/Ug73uSYTmSsAvhBUPj3uK3ECfU86cOPyqLUaavWfn+LhtfQidjPFe+sHs5HOXgfrl00c2ZteGb8NS+0p5Awj56Vy92WEjusCXK6t2B632G/ESiH0Cr3tiESHTvV2oFKWzosqGZgEfW+ntm6CvxgQqn5iiTBXykwos/MbtibJv+slZdo7EYut2e47GMbR3DmVsXKduaXbk8Jc/d3T2MceAYx0lodCenMXK785jgPbAD9YblfgGkglier4hFGIXsfJ2CKdKMl9eiAARmKPXq5iofrVa+KedFuBGmiVhqJYN+M/FrXb+cH3HqDSohLaRfe91b5CkibuKh4d6hsDTFdtQk7ph15aoayvZywGEGYbLy2BBhUf5Cz9S9tMvVg878+0gNbCFxJlk6U4NsZGW1rKLJGF/WyKygtCkmMq6NoGfm407KXm2ppfBjzknnTICVEIuO4qp+UcEmYQR6iC2eCfUxWIv6d6tggjJDo6GbS8DB1VP9krhcfv8VYi+2Hc5o2K18ZGubYnBMbnHmHAzoFrH8qKSYnRrzIoRVao4uX1gy+aE5f4WSSF/bNTcYMaiyJK9aOkveKZxCHuQh24bDVkoJ4vRvlJXVXcVyI72vEew6GKXiqAMMCQyrgsY=
